# Generated by Django 4.0.6 on 2024-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
